library(textclean)
library(data.table)
library(flexdashboard)
library(rvest)
library(googlesheets)
library(readxl)
library(dplyr)
library(raster)
library(tidyverse)
library(data.table)
library(tools)
library(httr)
library(RSelenium)
library(jsonlite)
library(RSelenium)
library(httr)
library(rvest)
library(ttutils)
library(jsonlite)
library(remotes)
library(emayili)
library(dplyr)
library(curl)
library(openssl)
library(sys)
library(mailR)
library(knitr)
library(png)
library(mailR)
library(DT)
library(webshot)
library(stringdist)
library(dplyr)
library(curl)
library(openssl)
library(sys)
library(mailR)
library(printr)
library(png)
library(mailR)
library(DT)
library(webshot)
library(ggpubr)
library(png)
library(grid)
library(gridExtra)
library(tidyquant)
library(pracma)
library(magrittr)
library(modelplotr)
library(ggplot2)
library(plotly)
library(knitr)
library(kableExtra)



setwd(paste0(wspc,"Fotmob Soccer Modelling"))
source("book_functions.R")

##### Getting the Team Library #####
sport_codes <- read_xlsx("book_codes_all.xlsx", sheet = "overall")
sport_matt_id <- 4
leagues_df <- data.frame(read_xlsx("book_codes_all.xlsx",sheet = sport_codes$dk_code[sport_codes$mattid==sport_matt_id]), stringsAsFactors = F)
leagues_df[is.na(leagues_df)] <- ""	
matt_id <- 8
leagues_df$b_code_2[leagues_df$b_code_2=="a-league_men"] <- "a-league"
whsa <- barstool_games(sport_codes,sport_matt_id,leagues_df,matt_id)
c(unique(whsa$BARSTOOL_TEAM1),unique(whsa$BARSTOOL_TEAM2))
